### PR TITLE
Create test68141.sql

### PR DESCRIPTION
**Pull request by sbaranwal10**

### CODE REVIEW

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
SELECT * FROM employee631211114212 CROSS JOIN orders21 order by employee84.id;
```

<details>
<summary>📊 Parser Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Avoid cross joins | Consider using an inner join instead. | CROSS JOIN is used between tables: EMPLOYEE631211114212 and ORDERS21. | [**↗️Navigate to line 1**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR1) |
| 2 | Avoid using ORDER BY without LIMIT | Consider using LIMIT when ORDER BY is used. | ORDER BY clause without LIMIT at line 1 | [**↗️Navigate to line 1**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR1) |
| 3 | Avoid SELECT * | Review the query to ensure that only the necessary columns are specified. | Scanning all columns of a table, SELECT * results in expensive and resource-intensive queries, but users often do not need all the columns. | [**↗️Navigate to line 1**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR1) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **NA** |
| 2 | Compilation | **❌** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
SELECT * FROM employee631141311212 CROSS JOIN orders21 order by employee84.id;
```

<details>
<summary>📊 Parser Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Avoid cross joins | Consider using an inner join instead. | CROSS JOIN is used between tables: EMPLOYEE631141311212 and ORDERS21. | [**↗️Navigate to line 3**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR3) |
| 2 | Avoid using ORDER BY without LIMIT | Consider using LIMIT when ORDER BY is used. | ORDER BY clause without LIMIT at line 3 | [**↗️Navigate to line 3**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR3) |
| 3 | Avoid SELECT * | Review the query to ensure that only the necessary columns are specified. | Scanning all columns of a table, SELECT * results in expensive and resource-intensive queries, but users often do not need all the columns. | [**↗️Navigate to line 3**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR3) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **NA** |
| 2 | Compilation | **❌** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
SELECT *
 FROM employee691211311122
 CROSS JOIN orders2721
 order by employee6912.id;
```

<details>
<summary>📊 Parser Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Avoid cross joins | Consider using an inner join instead. | CROSS JOIN is used between tables: EMPLOYEE691211311122 and ORDERS2721. | [**↗️Navigate to line 5**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR5) |
| 2 | Avoid using ORDER BY without LIMIT | Consider using LIMIT when ORDER BY is used. | ORDER BY clause without LIMIT at line 8 | [**↗️Navigate to line 8**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR8) |
| 3 | Avoid SELECT * | Review the query to ensure that only the necessary columns are specified. | Scanning all columns of a table, SELECT * results in expensive and resource-intensive queries, but users often do not need all the columns. | [**↗️Navigate to line 5**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR5) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **NA** |
| 2 | Compilation | **❌** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
Alter Table Employee;
```

<details>
<summary>📊 Profile Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Selected more than 20 columns | Review the query to ensure that only the necessary columns are specified. | Scanning more than 20 columns of a table results in expensive and resource-intensive queries, but users often do not need all the columns | [**↗️Navigate to line 10**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR10) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **NA** |
| 2 | Compilation | **❌** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
SELECT * FROM table131111212 INNER JOIN table4 order by table1.id limit 10;
```

<details>
<summary>📊 Parser Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Avoid SELECT * | Review the query to ensure that only the necessary columns are specified. | Scanning all columns of a table, SELECT * results in expensive and resource-intensive queries, but users often do not need all the columns. | [**↗️Navigate to line 13**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR13) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **NA** |
| 2 | Compilation | **❌** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Comment by sbaranwal10** [comment]
Logo

📌 **Query:**
```sql
select WR_ORDER_NUMBER,WR_ITEM_SK from sfsalesshared_sfc_samples_va3_sample_data.tpcds_sf100tcl.web_returns where wr_fee >= 0.22 order by WR_ORDER_NUMBER;
```

<details>
<summary>📊 Parser Based Insights</summary>

| # | Name | Action | Detail | Let's Navigate |
| --- | --- | --- | --- | --- |
| 1 | Avoid using ORDER BY without LIMIT | Consider using LIMIT when ORDER BY is used. | ORDER BY clause without LIMIT at line 15 | [**↗️Navigate to line 15**](https://github.com/unraveldata-org/snowflake-ci-cd/pull/42/files#diff-5b5ee9967bf22460857cdc40eafa6b5f196e55a7b63327adad41df952b3129cfR15) |
</details><details>
<summary>📋 Details</summary>

| # | Attribute | Value |
| --- | --- | --- |
| 1 | Bytes Scanned | **353.73 GB** |
| 2 | Compilation | **✅** |
| 3 | Max Estimated Cost | **NA** |
| 4 | Min Estimated Cost | **NA** |
</details>

**Review by saikotmajumdar — APPROVED** [review]

**Pull request closed without merging**
